# Generated by Django 5.2.5 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_user_date_joined_user_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='2', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
