# Generated by Django 5.2.5 on 2025-09-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(null=True, verbose_name='تلفن'),
        ),
    ]
