# Generated by Django 5.2.5 on 2025-08-13 11:49

import arashsport.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=16, prefix='ven_', unique=True, verbose_name='شماره')),
                ('name', models.CharField(max_length=100, verbose_name='نام فروشنده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to=arashsport.models.vendor_image_path, verbose_name='تصویر')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('contact', models.CharField(max_length=100, verbose_name='شماره تماس')),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
            },
        ),
    ]
