# Generated by Django 5.2.5 on 2025-08-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0002_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام فروشگاه'),
        ),
    ]
