# Generated by Django 5.2.5 on 2025-08-23 12:06

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0003_alter_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=14, prefix='p_', unique=True, verbose_name='شماره')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('off_price', models.PositiveIntegerField(verbose_name='قیمت با تخفیف')),
                ('status', models.CharField(choices=[('draft', 'در حال تکمیل'), ('rejected', 'حذف شده'), ('in review', 'در حال بررسی'), ('published', 'تایید شده')], default='in review', max_length=10, verbose_name='وضعیت کالا')),
                ('in_stack', models.BooleanField(default=False, verbose_name='موجود؟')),
                ('featured', models.BooleanField(default=False, verbose_name='محصول ویژه؟')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='arashsport.category', verbose_name='دسته بندی')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='arashsport.vendor', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='arashsport.product')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
    ]
