# Generated by Django 5.2.5 on 2025-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0004_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='off_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف'),
        ),
    ]
