# Generated by Django 5.2.5 on 2025-08-24 16:04

import arashsport.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0006_alter_productimage_options_alter_product_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stack_number',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجود در انبار'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=arashsport.models.product_image_path, verbose_name='تصویر'),
        ),
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('status', models.CharField(choices=[('process', 'در حال انجام'), ('shipping', 'در حال ارسال'), ('delivered', 'تحویل داده شده')], max_length=50, verbose_name='وضعیت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='تعداد')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت نهایی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='arashsport.cartorder', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_order', to='arashsport.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'کالا سفارش',
                'verbose_name_plural': 'کالا های سفارش',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('rate', models.CharField(blank=True, choices=[('1', '۱'), ('2', '۲'), ('3', '۳'), ('4', '۴'), ('5', '۵')], max_length=5, null=True, verbose_name='نمره')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='arashsport.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='UserWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='arashsport.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_list', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فهرست آرزو',
                'verbose_name_plural': 'فهرست آرزوها',
            },
        ),
    ]
