# Generated by Django 5.2.5 on 2025-08-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0007_product_stack_number_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(blank=True, choices=[('1', '۱'), ('2', '۲'), ('3', '۳'), ('4', '۴'), ('5', '۵')], null=True, verbose_name='نمره'),
        ),
    ]
