# Generated by Django 5.2.5 on 2025-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0008_alter_productreview_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0, verbose_name='امتیاز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')], null=True, verbose_name='نمره'),
        ),
    ]
