# Generated by Django 5.2.5 on 2025-08-28 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0009_product_rate_alter_productreview_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rate',
        ),
    ]
