# Generated by Django 5.2.5 on 2025-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0010_remove_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='امتیاز'),
        ),
    ]
