# Generated by Django 5.2.5 on 2025-09-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0012_alter_product_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
