# Generated by Django 5.2.5 on 2025-09-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0014_alter_product_description_alter_vendor_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stack',
            field=models.PositiveIntegerField(default=0, verbose_name='مقدار موجودی'),
        ),
    ]
