# Generated by Django 5.2.5 on 2025-09-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0015_product_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stack',
        ),
    ]
