# Generated by Django 5.2.5 on 2025-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arashsport', '0017_delete_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='status',
            field=models.CharField(choices=[('process', 'در حال انجام'), ('shipping', 'در حال ارسال'), ('delivered', 'تحویل داده شده')], default='process', max_length=50, verbose_name='وضعیت'),
        ),
    ]
